[package]
name = "randtools"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
test-case = { git = "https://github.com/frondeus/test-case.git", branch = "master" }
